### ISSUE TITLE
Restaurants CRUD

### ISSUE THREAD

**Issue by yagoprazim** [Ubifood-unipetech/Ubifood-backend#10]
## SUMMARY:

We need an endpoint that allows us to perform a complete CRUD of the restaurants that will be part of the application.

## TO DO:
1. Create a model called **"Restaurant"**, containing the following fields:

```python
class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField(max_length=100)
    banner = models.ImageField(upload_to='restaurants/banners/', null=True, blank=True)
    coordinates = models.PointField()
    group = models.ForeignKey(Group, on_delete=models.PROTECT)
    cpfcnpj = models.CharField(max_length=14)
```
-----------------------------------------------------------------------------------------
2. Create a serializer and a viewset so that a CRUD can be carried out in a practical way for restaurants.
-----------------------------------------------------------------------------------------
3. The endpoint must be: https://backend.unifood.lat/api/restaurants/
-----------------------------------------------------------------------------------------

**Comment by Kosolov325** [comment]
.
