### ISSUE TITLE
Products CRUD

### ISSUE THREAD

**Issue by yagoprazim** [Ubifood-unipetech/Ubifood-backend#11]
## SUMMARY:

We need endpoints that allow us to perform a complete CRUD of the products that a restaurant may have, as well as the categories that the products are part of.

## TO DO:
1. Create 2 models: 
a) **"ProductType"** (Which will correspond to the product categories); 
b) **"Product"** (Which will correspond to the products themselves).

```python
class ProductType(models.Model):
    name = models.CharField(max_length=50)
    mnemo = models.SlugField(max_length=20)
    icon = models.ImageField(upload_to='assets/product/types/icons/', null=True, blank=True)

class Product(models.Model):
    type = models.ForeignKey(ProductType, on_delete=models.SET_NULL, null=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    label = models.CharField(max_length=50)
    desc = models.CharField(max_length=100)
    icon = models.ImageField(upload_to='assets/product/images/')
```
-----------------------------------------------------------------------------------------
2. Create a serializer and a viewset so that a CRUD can be carried out in a practical way for the two models.
-----------------------------------------------------------------------------------------
3. The endpoints must be: 
a) https://backend.unifood.lat/api/product/types/
b) https://backend.unifood.lat/api/products/
-----------------------------------------------------------------------------------------

**Comment by Kosolov325** [comment]
.
