### ISSUE TITLE
Authentication JWT

### ISSUE THREAD

**Issue by yagoprazim** [Ubifood-unipetech/Ubifood-backend#9]
## SUMMARY:

It is necessary to implement an API that allows users to register, log in and log out in application, therefore, we need to create an authentication system for the application.

## TO DO:
Use Django's standard 'USER' rules to create the authentication system, implementing JWT, and providing endpoints for: registration, login and logout.

1. At the registration endpoint, the fields required for user registration must be:
```json
//FIELDS EXAMPLE
{
  "username":"Felicatos",
  "first_name":"Felix",
  "last_name":"Calado",
  "password":"zxcd1236"
}
```
- The endpoint should be called of: https://backend.unifood.lat/api/register/
-----------------------------------------------------------------------------------------
2. At the login endpoint, the fields required for user login must be:
```json
//FIELDS EXAMPLE
{
  "username": "Felicatos",
  "password": "zxcd1236"
}
```
- The endpoint should be called of: https://backend.unifood.lat/api/login/
-----------------------------------------------------------------------------------------
3. To log out, simply overwrite the endpoint's DELETE method so that, if the user is logged in, the logout occurs.

- The endpoint should be called of: https://backend.unifood.lat/api/logout/
-----------------------------------------------------------------------------------------
> [!NOTE]
> - [ ] 0 - Esforceless
>- [x] 1 - **Very Easy**
>- [ ] 2 - Easy
>- [ ] 3 - Not so easy
>- [ ] 5 - Medium
>- [ ] 8 - Hard
>- [ ] 13 - Very hard
>- [ ] ? - May god have mercy

**Comment by Kosolov325** [comment]
> [!NOTE]
> - [ ] 0 - Sem esforço
>- [x] 1 - **Muito fácil**
>- [ ] 2 - Fácil
>- [ ] 3 - Um pouco difícil
>- [ ] 5 - Médio
>- [ ] 8 - Difícil
>- [ ] 13 - Muito difícil
>- [ ] ? - Não tenho certeza

**Comment by Kosolov325** [comment]
### Time elapsed

| Time estimate | Time spent |
| -------------- | ---------- |
|1 day | 2 hours|
